apiVersion: v1
kind: Service
metadata:
  labels:
    tier: server1
  name: kubetest1
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      name: http
      targetPort: 5000
  selector:
    tier: server1
  type: LoadBalancer
